notifications:
  commits: commits@logging.apache.org
  issues: dev@logging.apache.org
  pullrequests: dev@logging.apache.org
  jira_options: link label
github:
  description: >
    Apache Logging Services Jenkins pipelines and shared libraries.
  homepage: https://ci-builds.apache.org/job/Logging/
  labels:
    - apache
    - jenkins-pipeline
    - library
